/**
 * nn_mfront.hxx
 * =============
 * Generic header for integrating TensorFlow neural networks into MFront
 * behaviours via cppflow.
 *
 * This header provides:
 *   - Conversion utilities between TFEL math types and TensorFlow tensors
 *   - A configurable NN class template
 *   - A singleton loader
 *
 * Usage: @Include this file in your MFront @Includes block, then use the
 *        nmf:: namespace for all helpers.
 *
 * Author: generated by mfront_nn_toolkit
 */

#pragma once

#include "cppflow/cppflow.h"
#include <array>
#include <stdexcept>
#include <string>
#include <tuple>
#include <vector>

#include "TFEL/Math/fsarray.hxx"
#include "TFEL/Math/st2tost2.hxx"
#include "TFEL/Math/stensor.hxx"
#include "TFEL/Math/tvector.hxx"

namespace nmf {

// ============================================================
// Constants
// ============================================================

static constexpr unsigned short DIM = 3u; // Tridimensional
static constexpr size_t STENSOR_SIZE = 6;  // 3D symmetric tensor

// ============================================================
// Type aliases
// ============================================================

using Stensor   = tfel::math::stensor<DIM, double>;
using Stensor4  = tfel::math::st2tost2<DIM, double>;
using CppTensor = cppflow::tensor;

// ============================================================
// Conversion: TFEL → cppflow
// ============================================================

/**
 * Convert a TFEL symmetric tensor (stensor<3,double>) to a flat cppflow tensor of shape {6}.
 */
inline CppTensor stensor_to_tf(const Stensor& s) {
    return CppTensor(std::vector<double>(s.begin(), s.end()), {STENSOR_SIZE});
}

/**
 * Convert an array of N stensors to a cppflow tensor of shape {N, 6}.
 */
template <unsigned short N>
inline CppTensor stensor_array_to_tf(const tfel::math::fsarray<N, Stensor>& arr) {
    std::vector<double> data;
    data.reserve(N * STENSOR_SIZE);
    for (size_t i = 0; i < N; ++i)
        for (size_t j = 0; j < STENSOR_SIZE; ++j)
            data.push_back(arr[i][j]);
    return CppTensor(data, {static_cast<int64_t>(N),
                            static_cast<int64_t>(STENSOR_SIZE)});
}

/**
 * Convert a scalar double to a cppflow tensor of shape {1}.
 */
inline CppTensor scalar_to_tf(double v) {
    return CppTensor(std::vector<double>{v}, {1});
}

// ============================================================
// Conversion: cppflow → TFEL
// ============================================================

/**
 * Fill a pre-allocated stensor from a flat cppflow tensor (expects 6 values).
 */
inline void tf_to_stensor(const CppTensor& t, Stensor& r) {
    auto data = t.get_data<double>();
    for (size_t i = 0; i < STENSOR_SIZE; ++i)
        r[i] = data[i];
}

/**
 * Return a new stensor from a flat cppflow tensor.
 */
inline Stensor tf_to_stensor(const CppTensor& t) {
    Stensor r;
    tf_to_stensor(t, r);
    return r;
}

/**
 * Fill a pre-allocated st2tost2 from a flat cppflow tensor (expects 36 values).
 */
inline void tf_to_st2tost2(const CppTensor& t, Stensor4& r) {
    auto data = t.get_data<double>();
    for (size_t i = 0; i < STENSOR_SIZE; ++i)
        for (size_t j = 0; j < STENSOR_SIZE; ++j)
            r(i, j) = data[i * STENSOR_SIZE + j];
}

/**
 * Return a new st2tost2 from a cppflow tensor.
 */
inline Stensor4 tf_to_st2tost2(const CppTensor& t) {
    Stensor4 r;
    tf_to_st2tost2(t, r);
    return r;
}

/**
 * Fill an fsarray<N, Stensor> from a flat cppflow tensor of shape {N*6}.
 */
template <unsigned short N>
inline void tf_to_stensor_array(const CppTensor& t,
                                 tfel::math::fsarray<N, Stensor>& r) {
    auto data = t.get_data<double>();
    for (size_t i = 0; i < N; ++i)
        for (size_t j = 0; j < STENSOR_SIZE; ++j)
            r[i][j] = data[i * STENSOR_SIZE + j];
}

/**
 * Fill an fsarray<N, Stensor4> from a flat cppflow tensor of shape {N*36}.
 */
template <unsigned short N>
inline void tf_to_stensor4_array(const CppTensor& t,
                                  tfel::math::fsarray<N, Stensor4>& r) {
    auto data = t.get_data<double>();
    for (size_t i = 0; i < N; ++i)
        for (size_t j = 0; j < STENSOR_SIZE; ++j)
            for (size_t k = 0; k < STENSOR_SIZE; ++k)
                r[i](j, k) = data[i * STENSOR_SIZE * STENSOR_SIZE + j * STENSOR_SIZE + k];
}

/**
 * Fill an fsarray<N*M, Stensor4> from a cppflow tensor of shape {N, M, 6, 6}.
 * Used for cross-derivative blocks (e.g. dphi2_dalpha[i][j] for branch models).
 */
template <unsigned short N, unsigned short M>
inline void tf_to_stensor4_matrix(const CppTensor& t,
                                   tfel::math::fsarray<N * M, Stensor4>& r) {
    auto data = t.get_data<double>();
    for (size_t a = 0; a < N; ++a)
        for (size_t b = 0; b < M; ++b)
            for (size_t j = 0; j < STENSOR_SIZE; ++j)
                for (size_t k = 0; k < STENSOR_SIZE; ++k)
                    r[a * M + b](j, k) =
                        data[a * M * STENSOR_SIZE * STENSOR_SIZE +
                             b * STENSOR_SIZE * STENSOR_SIZE +
                             j * STENSOR_SIZE + k];
}

// ============================================================
// Model loader (singleton factory)
// ============================================================

/**
 * Return a lazily-initialised cppflow::model at the given path.
 * The model is loaded only once per path (one singleton per unique path).
 *
 * Usage:
 *   auto& m = nmf::get_model("../../model/norton_nn");
 */
inline cppflow::model& get_model(const std::string& path) {
    // A static local is initialised exactly once (C++11 guarantee).
    // Using a lambda allows us to pass the path at first call.
    static cppflow::model instance(path);
    return instance;
}

// ============================================================
// Numerical differentiation helper (optional, templated)
// ============================================================

/**
 * Compute a numerical Jacobian (st2tost2) of a function f: Stensor -> Stensor
 * around point x, with perturbation h.
 * Finite difference scheme: central differences.
 */
template <typename Func>
inline Stensor4 numerical_jacobian(Func f, const Stensor& x, double h = 1e-6) {
    Stensor4 J;
    for (size_t j = 0; j < STENSOR_SIZE; ++j) {
        Stensor xp = x;
        Stensor xm = x;
        xp[j] += h;
        xm[j] -= h;
        Stensor fp = f(xp);
        Stensor fm = f(xm);
        for (size_t i = 0; i < STENSOR_SIZE; ++i)
            J(i, j) = (fp[i] - fm[i]) / (2.0 * h);
    }
    return J;
}

} // namespace nmf
